version: "3"

services:
  app:
    build: .
    container_name: rag-api
    restart: always
    expose:
      - "8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app
    volumes:
      - model-cache:/app/model

  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

volumes:
  model-cache:
